apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictic-deployment
  labels:
    app: tictic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tictic
  template:
    metadata:
      labels:
        app: tictic
    spec:
      containers:
      - name: tictic
        image: sifytul/tictic:sha-160213311c0d8c36fa89839f6146024ab446a2f0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tictic-service
spec:
  selector:
    app: tictic
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
