name: Ci/cd pipeline

on:
  push:
    branches:
        - main
jobs:
    build:
        name: build the app
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            
            - name: log repo
              run: |
                echo "Hello ${{github.repository}}"
                echo "Bye"
